### ISSUE TITLE
implement relative host urls for templates

### ISSUE THREAD

**Issue by a-t-k** [KOBENDigital/Iconic#19]
Hey, my configuration run on IIS with virtual foders. So i get allways problems in the presentation.

When you change these places, it will be work fine.

**iconic.controller:** 
var prePatch = umbRequestHelper.convertVirtualToAbsolutePath("~/");
    $scope.overlay = {
        view: prePatch + "app_plugins/iconic/views/iconic.dialog.html",
        title: "Select an icon",

iconic.prevalues.controller
var prePatch = umbRequestHelper.convertVirtualToAbsolutePath("~/");
    $scope.createNewPackage = function () {
        var newItem = new Package();

        editorService.open({
            title: "Create new package",
            view: prePatch + "app_plugins/iconic/views/iconic.edit.dialog.html",
...
...
$scope.editPackage = function (pkg) {
        editorService.open({
            title: "Edit package",
            view: prePatch + "app_plugins/iconic/views/iconic.edit.dialog.html",
            "package": pkg
        });

iconic.prevalues.editor.controller
var prePatch = umbRequestHelper.convertVirtualToAbsolutePath("~/");
        $http.get(prePatch + "App_Plugins/Iconic/preconfigs.json").then(
            function (response) {
                $scope.preconfig = response.data.preconfigs;
            },

package.manifest
 "prevalues": {
        "fields": [
          {
            "label": "Packages configuration",
            "description": "Add the font packages you want to use",
            "key": "packages",
            "view": "/App_Plugins/Iconic/Views/iconic.prevalues.html"
          }
        ]

**Comment by skartknet** [comment]
That looks good. It would be great if you could create a PR with it? ;)
