### ISSUE TITLE
interface looks a little broken in v8

### ISSUE THREAD

**Issue by pgregorynz** [KOBENDigital/Iconic#22]
Its great that the package  is working in v8, however the picker and the dropdowns seem a little broken and need styling updates.

![image](https://user-images.githubusercontent.com/1634892/88479491-da211f00-cf92-11ea-88cb-b95d7f1016a5.png)

![image](https://user-images.githubusercontent.com/1634892/88479503-e907d180-cf92-11ea-93c2-43dd10edef9f.png)

**Comment by skartknet** [comment]
Thanks Pete, I have reworked the styles. I hope you like it ;).
Fixed on new version 2.3.0
