### ISSUE TITLE
ValueConverter PackageCache uniqueKey

### ISSUE THREAD

**Issue by Migaroez** [KOBENDigital/Iconic#23]
When there are 2 properties with the same alias which use different packages, you can get the following error
"The given key was not present in the dictionary" in modelsbuilder.

**Comment by Migaroez** [comment]
@skartknet Have you had any chance to look at this and the associated pr?

**Comment by skartknet** [comment]
Hey @Migaroez , thank you for that PR! sorry I have been so busy lately. I'll include this in the next release.
