### ISSUE TITLE
Add to some Files the Virtual Path

### ISSUE THREAD

**Issue by a-t-k** [KOBENDigital/Iconic#25]
Version 2.3.1

Hey, some Files need add virtual path, because the application cant load some files and become a "http 404 not found" error.

**iconic.controller in "build" folder**

51 -> assetsService.loadCss('~/' + $scope.pckg.cssfile);

**iconic.dialog.controller in "buid" fodler**

18 -> assetsService.loadCss('~/' + pckg.cssfile).then(function () {

**package.manifest** make all references virtual add "~"

tx

**Comment by skartknet** [comment]
Thanks @a-t-k ! this will go on the next release.
