### ISSUE TITLE
v9

### ISSUE THREAD

**Issue by Migaroez** [KOBENDigital/Iconic#29]
Hey Mario, is there any roadmap to getting this awesome package to v9. Do you need help with this?

**Comment by skartknet** [comment]
Hi @Migaroez , I have been working on it. Hopefully I can have it ready soon, maybe 2 weeks max. Stay tuned!

**Comment by skartknet** [comment]
Thanks for the offer to help, really appreciated it.

**Comment by skartknet** [comment]
I have pushed version 3.0.0 as Nuget. @Migaroez could you give it a try please?

**Comment by skartknet** [comment]
Having an issue instaling the package:
![image](https://user-images.githubusercontent.com/1685262/143388545-2969887f-973d-40c2-a9d8-1eceeb3ba1d5.png)

That targets file is created automatically when I created the project with the dotnet tool. I used the 'pack' option on VS and it includes that targets file on the nuspec. I have removed it manually with Nuget Package Explorer but it's still complaining about it.

**Comment by skartknet** [comment]
Actually, maybe that's something with my local setup and there's nothing wrong with the nuget...

**Comment by skartknet** [comment]
working now. I had to publish v3.0.1

**Comment by Migaroez** [comment]
I will have a look at it now, sorry for missing all of this
