### ISSUE TITLE
Unable to configure Material Icons

### ISSUE THREAD

**Issue by uniquelau** [KOBENDigital/Iconic#3]
Hello,

The package looks great, but I'm struggling to get Material Icons setup.

I'm using your pre-define defination, and setting the CSS file to:

https://fonts.googleapis.com/icon?family=Material+Icons

However, what is expected of the `Rules source file` attribute? 

Many thanks! Laurence

**Comment by skartknet** [comment]
Hey Laurence,
I forgot to merge the 1.2 version branch into master! Sorry for that. The Readme has been updated with new instructions. You can see there how to configure the plugin for Material Icons. The Rules source file is here: https://github.com/google/material-design-icons/blob/master/iconfont/codepoints

**Comment by skartknet** [comment]
By the way, happy for some ideas to give another name to that file path, I just don't know what else I can call it :P

**Comment by uniquelau** [comment]
Aha! Perfect, that works! I'll have a bit of a think about naming :-)

Couple of other ideas:

1. If only one library is selected, the dropdown should default to this / default to first library
2. When re-opening the Icon picker, the selected Icon should be highlighted
3. If possible it would be nice to show the name / unicode of the selected icon, useful if the content editor wants to set other pages up with the same icon

**Comment by skartknet** [comment]
Awesome. I have opened independent tickets for this.
