### ISSUE TITLE
Can't save configuration in 3.1

### ISSUE THREAD

**Issue by Migaroez** [KOBENDigital/Iconic#32]
![image](https://user-images.githubusercontent.com/6025797/146645044-02c28464-a4ff-4f5a-aceb-e77105b46e31.png)
This is what happens if I click preconfigured and then go back to custom

If I just do custom straight away and start typing a name it doesn't allow any value
![image](https://user-images.githubusercontent.com/6025797/146645157-fe256f64-4047-4ce2-9308-eafbdbd06a79.png)

When just taking a preconfigured and selecting the 2 files, same as the first screenshot.

**Comment by skartknet** [comment]
Hi @Migaroez , you need to choose the `all.css` file, as the `brands.css` doesn't contain any rule for the icons.

Regarding the 'start typing a name it doesn't allow any value', I can't replicate, what doesn't allow any value?

**Comment by Migaroez** [comment]
The source file is a custom one from me so i can filter out certain icons, don't worry about that.

I immediately get a red box (see screenshot) for the name. Don't understand why.

**Comment by robertjf** [comment]
@skartknet I've also noticed that I need to provide a file for "Rules source file" in the current version as well in order for the Save button to become available... not sure if this is relevant or not...

**Comment by Migaroez** [comment]
This issue is solved in 3.1.1 (our.iconic)

I now see the actual error for the previewer
"The extracted icons are 0. Please check that the Selector regex is correct."
